apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: whoami
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/argocd.git
    targetRevision: HEAD
    path: whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
