apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dendrite-registrations
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/argocd.git
    targetRevision: HEAD
    path: messaging/registrations
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
