apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbg-prism
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/argocd.git
    targetRevision: HEAD
    path: mbg-prism
  destination:
    server: https://kubernetes.default.svc
    namespace: mbg-prism
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
