apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/argocd.git
    targetRevision: HEAD
    path: uptime-kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
