apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-alertmanager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-31.0.0
    directory:
      recurse: true
    syncOptions:
    - Replace=true
  - repoURL: 'https://github.com/rubenhensen/argocd.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true  
   
