apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAX3MGQ+AM43JmB5divs0YESrIMjHOAK+340D/w5H8oMPWqx2qTI2wO2dRv7M7DemlbPhIgFkWMRzDeWhU30f8yFCIBGIdfa66FGHrdsejnziQfF/ai3czCkUk5UjKdyLyad2QAIKjejO5F2x/FghkKmatn+cLxf65KpaO1os+DIoqLVlLAO10CSb+tR6Mm96TBZWAE9P+rQi1Ie0BZXImoYR+X8y+SeigA7ZAMgd0o49oiV4XQNLIoWvNDanzqfkFhwWPr3+qykC9Nl140D3IdNmKjj63pLsfPfi98K/h02tDE3Wcky8TzeY6RX9y0VsEtbYK5FDyWOSB35sCNJ69TuFMH9fMEygk4iGgeTqP7LmUxOcm0qOMoxslFrki71lfkDmP7V/lKve1jjITCakjeYB2jVD0Gc4bSU8O+6ddIVt5K0UKYWbjTKxI9PZJ4g+vH/Fha4HPeBy7yiSO4CtJ6/Y6XBBKI2KzZIL+CrNkJSqFsIQpH8FTu9O3amc/AE/IoBix0eVF0U73MOCcTKloRhPZ75jyl9AK5H6oemdnZKCR2ROFsqHbRsfZXv0UiCSXQSppb5WA6FeA6r9tO0SJ5lmWgWlxz6xBjC1L7EJ/m4CnkmtrPeNjeO4t/aiv2sgm6Q4H8O8vmgNJ0eElEx7tBaKfs4F8ogOxrtU+llyLjaoGQsBm6mZh7xbHmrgrWU8QIoiBwzfH9w9E434Ee2HPKjEuJCytsNIEVSg4bvnmfmzOgSOFC
    admin-user: AgAINlTPTAXzCcLunVvWRTG6GlnVUSY+6dg+YL70uyJVqs9CRbtJQ8hUg4UU1c3sXy5+rtdr7SxUoMDVfVrKKdwfAPLAxOYjwVNaFKPsi5rY+uacQ9AXWFMe+dUVkWtASkwQqepXeaA85BfzWRtW3JhLNvVXkvaVOc6XUjUCuq4Donocd3PC8MuOrWWS3CbJHHiTfjPs+jF7jsWH/qYb9XcyA99APvhUmXNjxcuCVsCWHIwjzwZgX9U7sgiLuu3zneOT83f3yBygywxpi2zhaa4rvmItnArUqpTfYIc2wQXOzd/JZJQ+VAl4R3pTmPuoz1jTVt1oK2Xsiq+/7QAbfk6E39ECdSjto3cbJDLc3hxZW4yDGhTghaQSpytnn56YIpyRFl81MYq1DwlyxqVbwc3Pbp4fxsxw6Dd6v3Pi+lIC7m7Qi5AL4nr7/qhTb8wI2ue+qBtZ7kbX3wArk9GZ+41Fu47kRuI1Yf5seaKIbSI+h0gUFeKYpcHajvX5gk2hdOkb+8x6O9KQfjv7NVbI+oJoyjv7Pvjk3IwWMnyvrOxnz5fo9OZvmDxrd8Ys2Pz6+huFftFrqoLNXHjPcYI7lcZMy2oEJrjo1XFfleIzCgm5QB8r1Ivz0X2djfQIqrROb1APhjadW1tUiYi1G6hB14mttFp0lga89sI0BLf3yig2ODM+Wq0DnqGdvr78Bgcra4ViBkW37A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque

