apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgDe9qV0CKxYha5QxS09Yuc429ksjYwortFVr+cQmO2XD5ajoZ+1lG/+GDu0tSORTwVPCBFNYpeSMV0rFdDiqUdRsRrdWszu0jcdA4Y9HTVnrmY15MDgt39TM9E0ylY7ZKzr3h4wyKkdpF5XotfMlRXVg3L1WzQfThkBjNIu9vCMR9bnZJm+kLSIFLIL8TXOub9b9YYkIcb9BflMfsYgWeTUTyesCBqtc2V19a2oNL+SHGZJ6m8ACyoZS2sw6OhSj3sCbDWT+wsTmpJH+Aa9fRwvRP6XKW55niLdG4We93B4AEvZp95+URf3R2dvkgmYU+NYtCsc6RW6Z6E5Mww4TX9/5hYsVENwPnwC2eSz+hdCPWNKf47LdUE7cJG8CIXu7eoMZEFQCzSnbY9hLAjTwDpWYGkbWq4EYlpLK59q6GYgcH4r60kUsTsL5QGoXrsJm6BtypaubX+QETS1PB/Jtkqzax5avp5EAKf1h0oOLyad1o9sRHKPKlMFrJhlxMSlapSloTIoL9HHMzMO3O9leEocEsCXCrOuxzOxjWdcYERdIgVENqtu5eww4cOrYqTDUmBuLKSxct6nT7BdARcpEapKM8a7cqjO2PwQszdHRWrcL/XRdKfUyepWCmYPNCHiktIQG7C7+vX/yLiJUbfbtMTVRVHdSHMeYU8XYGYY9KvgHor+z9r8dsb9x3O1//nbK/y781SYkJAbzKZnva5rNEIfONztLc4EDJEwXZ+LsAZYuzhECxwh
    admin-user: AgDEBc5N7RWh+enxLQ3kZ09oPU4aIVG5NHLNtvRfzqkWw7spph1Y3Icvj/IAvC2Ea3WYxOHZPdMYphDEFRkqJGezH/zKjXDcPScKhqaQvS5aSkyxoCCmGQYE6VF3W/++bQ1y+glOfF6WEYFt/KDYHCos0MvAUfqEjRYqur1LFC467MS8rDKmIE4wdZq8htQpik2E0+3ish13EfJxR/JmtHAlHPqjUq5NvTrbYJSNxKoL25DD4IDtiYl08LQ9G5lNqY3vvbPlMoqu/Ee/sJSig5yzC8O9V53HdeLp5pUxELSX/9RgpLA0rs3t5WizJik4fxZbOy7gBzDZn1XqvI9upAVq76awaEzzhEz4k6aljQg7GUOjy1XnWUDl5yGlASJjAUX0u2BUu6i1Hc4tBrKgr+8BqtdzjRsDVgqJZNWU6BYcy2yCGghfexEhDHPWYGgq5QvyJZSQuku1GEWDc64XF+fAim1nvtIzjXX5MfOYiQ6qPI0k8cF5ySxzzEk7hXJjWFPtHA8zxu2pEYWxDioyBFSWd9HPH6A2j5MtTHfYkXSaTq/hn7jXVLSd2c2otlOHYroPXz0zutkh0lJMqeK4C569Jbr9WM3PnIDRAzDgRHubFCZ6XwwsNTE6gUikfzFS26zDA03Ettbk83kXNZDb0LlwAg6pGiWmiW+GNIleaYdUHiGI7cHz7GB8H5KkA1AJdLxKYSvVkA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: kube-prometheus-stack
    type: Opaque

