apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring-three
spec:
  encryptedData:
    admin-password: AgCViW1uxxco24y0NJ+iPbL4mr/78Z8k7RudhyMf04pmWhKTF5jvqKU0JRiWE/QP2PHKyHg/T+bMB8HhytSJ/IVJGOdt3TuzdU4kdMmatw4Xiahfw/MGcEwkaopBiNcckU6RCXtAc+0LrWyj1XvGWRGTmTOC/0GSewp3BaoQpu85aN9gGm1XkLWPZxNNGffpCEPABEGv9W2KLShf55Zl0VP7dO1Oz2cCwx6S4cXMlORJHUlZV52B9dFt2FKEU8DJBHVOdQU67ZrZwh2xQlvCLI/qbVln2feH9HqdNjhp0DmW2DSNAwWwnanq0qSL6D8DsfB1yCaw6WK1WXSaRCMHdl0uBcdIz6CNlUzmL4mU5TCwD95x9+ovcrhJ4wAyXMZeztN+QJSm3U7AKM87RMmD2gA1XYnVotMGcX8b7wObMkwUsY5WYPUm+fwj4J6C4yEDzJZSTSggaQN2YZVjxuH2yb6BsMwDzTrjoGIsV8pxoTNM4ewHqM+bqfHyC7d+wGvZeNsocB/1JOl21UnenQb9/eDJc8orQGXCOpRzgYwFPNXxYJxL+1ZoWBtp5Z56Vgfma4BdzS2zLw9QOkSYd+7z2YHdhlS3HRWVYUyILh8P4NvIyZ0RoQVbD02jedaZ6s9YF58ISrKuF56Av+CjXbwWU+p1r8qOmY1bYrbCGDB3FlUvSU+dJFK6bHMLnt6ITN3ihMRl5iE1LyjgmgquSRfW11X2Im1LV+PNafWNdg4LO9K1ZqRNfPe+
    admin-user: AgA4mMPkVviMAJQUNt94b4Yl5YoFP5DBEtRfA3oYY1kmldRhMdQ4Q7dtMQlhrLobBI2j2y9bQzBCKvFeWea/GznlQv/HWvFzh4jDn8XR2fz3xNqnTS7/dZXE1bJRLdmYF/1xu5wcyHph733gNF+sdjjQ5VRyOS4wppvEPoRq3/1iDMS7YYwBX3u6EUR3pmLRv2ppKOkX3rOXeq0/wdKiB6LuyQw+aD/hCqZZDWwYmCyWbgMjadNexzFBDJacvcokaVR6au5ctNuCeVC4Iz0OFzMda0ziOymVk6dpgtyEU7/eeLFAdqaP1Jfw3F6wlSYd/PsPPIDmkk4cyE/LEB6K+Qtiso4Kq7QR8esT+5DtMM9BdViJDhwoxU6pSClaMgyFppBjU5HsdplsCNnptAfQ/I4Js0enlUdkvGsEAMc2MoHnatHAxZWhuvm1nuuxcGFKafUgQlzv+7AWyc0A12u9HW8lFWuahVc32Dp1zbWugU2+y+U9zb0+Ze+gmCf6oidCPfE0+TmQww3x7KUi+CV55Lmbg121jod0M/Gm24QsWRXl3K+jO3VIM9q5e9FUeXnURUtrZUX/Etf8z43S8RDmLosRMKOu0pJfphows4QbIdy5C5q0DxBc1pRRGk5D+7gvSEuihITJgtom79rJFLk1b95gtWfE+0LlYPQMUOg3OcSZhl/0XPpFlIxuz02vVl95pRyF0v1pWw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring-three
    type: Opaque

