apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
  - chart: grafana/loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 56.0.3
    helm:
      releaseName: loki
      valueFiles:
        - $values/monitoring/values-loki.yml
  - repoURL: 'https://github.com/rubenhensen/argocd.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    # - Replace=true
    automated:
      prune: true
      selfHeal: true