apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-alertmanager
  namespace: argocd
spec:
  project: default
  sources:
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.11.0
    helm:
      releaseName: kube-prometheus-stack
      # skipCrds: true
      valueFiles:
        - $values/monitoring/values.yml
  - repoURL: 'https://github.com/rubenhensen/argocd.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true