apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 50Gi
