apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBaa3OzxZBf0WOl5B2ig6B9qDEieSeqHz6lnk2EUT0jGQ/KtBB81MfaPZHFkZ5JDEuR/ND2KxUlPgTL985i/6SOESPDcjVvzqofR0rH6y+pg6Ma7aMTJ2j7S7YfDTSUXX0V0Fu1rd9cAvMqXPYITLQvk4oduk1HKFMrfk8oJ47/24VC8ceWSUgEyPiN1MCfDAO+JGfKoz51JrENgGCACe1KMrDBsD1qVNXTPyEI4pammXItBs7QsppBvjWUMGVyu+iT9hEK7n3htXQViiXjFTwV70wPkth7U1fM3cuKOAYpMluLKbEIfMFPhb41w8zWzv0RqRXvv6xz8SvqtLx/kIMgNFyF8OoECmp1izlcWHuPmErvWI0ZyDPWr6h16n/jYHiEM5kmp0qaV6rEUoToP/no9tOGorPc7UkMhszYjQ0k3Cw4cBosNefm6tT/sR+xXtas2h6Xfl0hMbH+++cH70zhhsdOunx/mteZgy8wGJGR8jFWfHX+IAd98av2lGdd5J4LYd9kMDdxgVCdbNvcVJtLXXk6xdhZjGilHgdeVefhjL4dwAAZN49K+vSmW8GrpsQaSyJJU/6MQrzWpVd0KvX3w6KT7ZbTObW06A0SKVYBDT+el+5sP99zeaP4FZTLnswMe3Rpyf3l0dvH7WxzWYsgtudJgHj4W2c+6Xx1PZ11nvkg8yrcjrt2wHPj+TEKOWqZYVYfFDmFqubaeF2eltofmDSEwbfsTCScGBa1ZQgB1yxTjs6N
    admin-user: AgCACbObGn2IIpNqa4CjlXhO6ryoF4EfDLa6cDGDsnpyAJu6GS4kUxKDPa2poLoaaOeioPSVzICjTcP1hvtjpdpSjlVa7KlBF/tbbM4aSy9yzR/Zzr1HMCsLb8+bWPBEMgcxB2c/cmx7KfKIWpqzSKU320rqzkdx1HK8UkrPNG0uB2fKbDO1eF9esmynIIrZ0uiJnPZDWUflJI1KCjK/K/qwDmrBSBh0oztOh9YMA6Z9+Zusc3sKht8IVtAO3rURoDQ7io2Py+5strazhEaIsHR6Hbf6hTpy3yoSm6jlmW49EIaAZKcLHueFDmNkQZ0lAJa3a9OrYleQUdW1P3l8QSkGg1QaE21tVDA4ZiaK7pimppGc/ValjYV4uNdHmzKSH6E2vhpr/VNyFXXdNJVqIWoAf3Br+t1BkW8hcZpmnx3DKooHbt8vPqgOz7oHDUNnIBDGUb4KoTrs9y0R7X9Sfc87WDUEoULytxvCcgp+JeEBgtDzTqG5vIVK4bdULh2c3aatZOV/IaQEwTEjvX5MCjhiCm+vMyGeUbWc+i+DxTx2IyYJ8y4sg40kOHmr9LmGWPsI6rofJTmABcZtOiBgzlgolJ4bnQm7dBnda7Mh2PmAFmuxAP98MgmkJ9jcuRot8uJuGXNFNZ6Kya/O+G4kpZ0JHCUHLA0XX0KW5/YzFH6SgEsMn/kqtGanSu2zN58qZ209E1eMIQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque

