apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.7.0
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus-stack