kind: Deployment
apiVersion: apps/v1
metadata:
  name: dyndns
  labels:
    app: dyndns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyndns
  template:
    metadata:
      labels:
        app: dyndns
    spec:
      containers:
        - name: dyndns
          image: hebury/dyndns:1.16
          volumeMounts:
            - name: secret-vol
              mountPath: "/etc/go-transip-dyndns"
              subPath: "go-transip-dyndns"
              readOnly: true
      volumes:
      - name: secret-vol
        secretName:
          name: go-transip-dyndns.toml