kind: Deployment
apiVersion: apps/v1
metadata:
  name: dyndns
  labels:
    app: dyndns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyndns
  template:
    metadata:
      labels:
        app: dyndns
    spec:
      containers:
        - name: dyndns
          image: hebury/dyndns:1.17
          volumeMounts:
            - name: secret-vol
              mountPath: "/my-config"
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /my-config/go-transip-dyndns.toml /etc/go-transip-dyndns.toml
      volumes:
      - name: secret-vol
        secretName:
          name: go-transip-dyndns.toml