kind: Deployment
apiVersion: apps/v1
metadata:
  name: dyndns
  labels:
    app: dyndns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyndns
  template:
    metadata:
      labels:
        app: dyndns
    spec:
      containers:
        - name: dyndns
          image: hebury/secret-test:1.3
          volumeMounts:
            - name: secret-vol
              mountPath: "/secret"
              readOnly: true
            - name: config
              mountPath: "/config"
              readOnly: true
    volumes:
    - name: secret-vol
      secret:
        secretName: transip-api-ssh
    - name: config
      configMap:
        name: dyndns-config