kind: Deployment
apiVersion: apps/v1
metadata:
  name: dyndns
  labels:
    app: dyndns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyndns
  template:
    metadata:
      labels:
        app: dyndns
    spec:
      containers:
        - name: dyndns
          image: hebury/dyndns:1.20
          volumeMounts:
            - name: secret-vol
              mountPath: /secret
              read-only: true
            - name: config-vol
              mountPath: /config
              read-only: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - >
                    cp /config/go-transip-dyndns.toml /etc/go-transip-dyndns.toml
      volumes:
      - name: secret-vol
        secret:
          secretName: transip-key
      - name: config-vol
        configMap:
          name: go-transip-dyndns-configmap