apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dyndns
spec:
  project: default
  source:
    repoURL: https://github.com/rubenhensen/argocd.git
    targetRevision: HEAD
    path: dyndns
  destination:
    server: https://kubernetes.default.svc
    namespace: dyndns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
