# kubectl create configmap go-transip-dyndns-configmap --from-file=dyndns/go-transip-dyndns.toml --dry-run=client -o yaml > dyndns/dyndns-configmap.yml

[general]
#
# Enable verbose mode (debugging information).
# Disabled by default.
#
verbose = false

#
# Pull in your public IPv4 address.
#
IPv4 = true

#
# Pull in your public IPv6 address.
# Only use when you have an IPv6 address.
#
IPv6 = false

#
# Update in keep running mode every x (in minutes)
#
update-frequency = 1

[account]
#
# Your account name on transip.
#
username = "hebury"
#
# Private key to get access the API.
# Create your own key here: https://www.transip.nl/cp/account/api/.
#
# You have two options here.
# Include the private key in the configuration file.
#
# Example:
# private-key = """-----BEGIN PRIVATE KEY-----
#...Your certificate data...
#-----END PRIVATE KEY-----"""
#
# or
#
# provide the path to the file that contains the private key.
#
# Example:
# private-key = "/secret-vol/transip-api-ssh/ssh-privatekey"
#
# Mind the """content""" (3x) quote for including the key in the config and the "path" (1) for the path...
#
private-key = "/secret/transip.key"

#
# The DNS record you want to update.
# You can have as many as you want.
#
#[[record]]
#
# the domain name where the record should be updated.
#
#hostname = "example.com"
#
# The entry key for the domain
# in this example my-home.example.com is the full dns entry we are creating here.
#
# use @ if you want to redirect the root domain.
#
#entry = "my-home"
#
# The caching time in seconds.
#
#ttl = 60
#
# The record type.
# A for IPv4
# AAAA for IPv6
# but can also be MX TXT SRV
#
#type = "A"
#
# content that will be pushed into the record.
# this value is ignored for A and AAAA records.
# for other records you can use the placeholders {{.IPv4}} and {{.IPv6}}
# to inject the IP's
#
# content = ""

[[record]]
hostname = "hensen.io"
entry = "@"
ttl = 60
type = "A"
content = ""

[[record]]
hostname = "hensen.io"
entry = "dev"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "argocd"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "drive"
ttl = 86400
type = "CNAME"
content = "rubenhensen.synology.me."

[[record]]
hostname = "hensen.io"
entry = "ftp"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "argocd"
ttl = 86400
type = "CNAME"
content = "cname.vercel-dns.com."

[[record]]
hostname = "hensen.io"
entry = "mail"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "mbg"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "nas"
ttl = 86400
type = "CNAME"
content = "rubenhensen.synology.me."

[[record]]
hostname = "hensen.io"
entry = "photos"
ttl = 86400
type = "CNAME"
content = "rubenhensen.synology.me."

[[record]]
hostname = "hensen.io"
entry = "staging"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "mbgupload"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "whoami"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "www"
ttl = 86400
type = "CNAME"
content = "@"

[[record]]
hostname = "hensen.io"
entry = "www"
ttl = 86400
type = "TXT"
content = "v=DMARC1; p=none;"

[[record]]
hostname = "hensen.io"
entry = "transip-a._domainkey"
ttl = 86400
type = "CNAME"
content = "_dkim-A.transip.email."

[[record]]
hostname = "hensen.io"
entry = "transip-b._domainkey"
ttl = 86400
type = "CNAME"
content = "_dkim-B.transip.email."

[[record]]
hostname = "hensen.io"
entry = "transip-c._domainkey"
ttl = 86400
type = "CNAME"
content = "_dkim-C.transip.email."

[[record]]
hostname = "hensen.io"
entry = "@"
ttl = 300
type = "TXT"
content = "v=spf1 ~all"

[[record]]
hostname = "hensen.io"
entry = "@"
ttl = 86400
type = "TXT"
content = "10 @"