generatorOptions:
  disableNameSuffixHash: true # this flag is used to avoid creation of new configmap, instead it will be modified when file context is changed
configMapGenerator:
- name: go-transip-dyndns-configmap
  files:
  - go-transip-dyndns.toml

resources:
- transip-key-sealed.yml
- update-dns-hook.yml