apiVersion: batch/v1
kind: Job
metadata:
  name: dyndns-postsync-hook
  generateName: dyndns-sync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation 
spec:
  template:
    spec:
      containers:
      - name: dyndns
        image: hebury/dyndns:1.22
        volumeMounts:
          - name: secret-vol
            mountPath: /secret
            readOnly: true
          - name: config-vol
            mountPath: /config
            readOnly: true
      restartPolicy: Never
      volumes:
      - name: secret-vol
        secret:
          secretName: transip-key
      - name: config-vol
        configMap:
          name: go-transip-dyndns-configmap

  backoffLimit: 2