apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: has-influxdb-data
  namespace: has
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi