apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32766
  type: LoadBalancer
  externalTrafficPolicy: Local
  healthCheckNodePort: 32767