apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
## changes to config maps
namespace: argocd
patches:
- path: overlays/argo-cmd-param-cm.yaml
