apiVersion: v1
kind: Service
metadata:
  name: whatsapp
  labels:
    app: whatsapp
spec:
  ports:
    - port: 29318
      protocol: TCP
      targetPort: 29318
      name: http
  type: ClusterIP
  selector:
    app: whatsapp


