apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-to-album-redirectregex
spec:
  redirectRegex:
    regex: ^https?:\/\/foto.scoutingmbg.nl\/?
    replacement: https://foto.scoutingmbg.nl/library/albums
