apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      containers:
        - args:
            - --innodb-buffer-pool-size=512M
            - --transaction-isolation=READ-COMMITTED
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --max-connections=512
            - --innodb-rollback-on-timeout=OFF
            - --innodb-lock-wait-timeout=120
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MARIADB_DATABASE
              value: photoprism
            - name: MARIADB_INITDB_SKIP_TZINFO
              value: "1"
            - name: MARIADB_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism2
                  key: MARIADB_PASSWORD_READONLY
            - name: MARIADB_ROOT_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism2
                  key: MARIADB_ROOT_PASSWORD_READONLY
            - name: MARIADB_USER
              value: photoprism
          image: mariadb:11
          name: mariadb
          resources:
            requests:
              memory: 10 Mi
            limits: 
              memory: 8 Gi
              cpu: "8"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-claim2
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: mariadb-claim2
          persistentVolumeClaim:
            claimName: mariadb-claim2
status: {}
