apiVersion: apps/v1
kind: Deployment
metadata:
  argocd.argoproj.io/sync-wave: "1"
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tools\kompose\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/mbg-prism-default: "true"
        io.kompose.service: mariadb
    spec:
      containers:
        - args:
            - --innodb-buffer-pool-size=512M
            - --transaction-isolation=READ-COMMITTED
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --max-connections=512
            - --innodb-rollback-on-timeout=OFF
            - --innodb-lock-wait-timeout=120
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MARIADB_DATABASE
              value: photoprism
            - name: MARIADB_INITDB_SKIP_TZINFO
              value: "1"
            - name: MARIADB_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: MARIADB_PASSWORD 
            - name: MARIADB_ROOT_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: MARIADB_ROOT_PASSWORD 
            - name: MARIADB_USER
              value: photoprism
          image: mariadb:11
          name: mariadb
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-claim0
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: mariadb-claim0
          persistentVolumeClaim:
            claimName: mariadb-claim0
status: {}
