apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
    spec:
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        command:
        - chown
        - -R
        - mysql:mysql
        - /var/lib/mysql
      containers:
        - args:
            - --innodb-buffer-pool-size=512M
            - --transaction-isolation=READ-COMMITTED
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --max-connections=512
            - --innodb-rollback-on-timeout=OFF
            - --innodb-lock-wait-timeout=120
          env:
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
            - name: MARIADB_DATABASE
              value: photoprism
            - name: MARIADB_INITDB_SKIP_TZINFO
              value: "1"
            - name: MARIADB_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: MARIADB_PASSWORD 
            - name: MARIADB_ROOT_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: MARIADB_ROOT_PASSWORD 
            - name: MARIADB_USER
              value: photoprism
          image: mariadb:11
          name: mariadb
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-claim1
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: mariadb-claim1
          persistentVolumeClaim:
            claimName: mariadb-claim1
status: {}
