apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  ports:
    - name: http
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
status:
  loadBalancer: {}
