apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-claim2
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 200Gi
status: {}
