apiVersion: v1
kind: Service
metadata:
  argocd.argoproj.io/sync-wave: "0"
  annotations:
    kompose.cmd: C:\tools\kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mbg-photoprism
  name: mbg-photoprism
spec:
  ports:
    - name: http
      port: 2342
      targetPort: 2342
  selector:
    io.kompose.service: mbg-photoprism
status:
  loadBalancer: {}
