apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-claim3
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 10Gi
status: {}
