apiVersion: v1
kind: Service
metadata:
  name: mbg-photoprism-upload-svc
spec:
  ports:
    - name: http-svc
      port: 2342
      targetPort: http
  selector:
    app: mbg-photoprism-upload
status:
  loadBalancer: {}
