apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  name: mbg-photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbg-photoprism
  template:
    metadata:
      labels:
        app: mbg-photoprism
    spec:
      containers:
        - env:
            - name: PHOTOPRISM_ADMIN_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: PHOTOPRISM_ADMIN_PASSWORD 
            - name: PHOTOPRISM_ADMIN_USER 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: PHOTOPRISM_ADMIN_USER 
            - name: PHOTOPRISM_AUTH_MODE 
              value: password
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_DATABASE_NAME
              value: photoprism
            - name: PHOTOPRISM_DATABASE_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mbg-photoprism
                  key: MARIADB_PASSWORD 
            - name: PHOTOPRISM_DATABASE_SERVER
              value: mariadb:3306
            - name: PHOTOPRISM_DATABASE_USER
              value: photoprism
            - name: PHOTOPRISM_DEFAULT_TLS
              value: "true"
            - name: PHOTOPRISM_DETECT_NSFW
              value: "false"
            - name: PHOTOPRISM_DISABLE_CHOWN
              value: "true"
            - name: PHOTOPRISM_DISABLE_CLASSIFICATION
              value: "false"
            - name: PHOTOPRISM_DISABLE_FACES
              value: "false"
            - name: PHOTOPRISM_DISABLE_RAW
              value: "false"
            - name: PHOTOPRISM_DISABLE_SETTINGS
              value: "true"
            - name: PHOTOPRISM_DISABLE_TENSORFLOW
              value: "false"
            - name: PHOTOPRISM_DISABLE_TLS
              value: "false"
            - name: PHOTOPRISM_DISABLE_VECTORS
              value: "false"
            - name: PHOTOPRISM_DISABLE_WEBDAV
              value: "false"
            - name: PHOTOPRISM_EXPERIMENTAL
              value: "false"
            - name: PHOTOPRISM_HTTP_COMPRESSION
              value: gzip
            - name: PHOTOPRISM_JPEG_QUALITY
              value: "85"
            - name: PHOTOPRISM_LOG_LEVEL
              value: info
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: "5000"
            - name: PHOTOPRISM_RAW_PRESETS
              value: "false"
            - name: PHOTOPRISM_READONLY
              value: "true"
            - name: PHOTOPRISM_SITE_AUTHOR
              value: Scouting MBG
            - name: PHOTOPRISM_SITE_CAPTION
              value: Foto's scouting MBG
            - name: PHOTOPRISM_SITE_DESCRIPTION
              value: Foto's scouting MBG
            - name: PHOTOPRISM_SITE_URL
              value: https://mbg.hensen.io
            - name: PHOTOPRISM_UPLOAD_NSFW
              value: "false"
          image: photoprism/photoprism:latest
          name: mbg-photoprism
          ports:
            - containerPort: 2342
              hostPort: 2342
              protocol: TCP
              name: http
          resources: {}
          volumeMounts:
            - mountPath: /photoprism/originals
              name: photoprism-claim2
            - mountPath: /photoprism/storage
              name: photoprism-claim3
          workingDir: /photoprism
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: photoprism-claim2
          readOnly: true
          persistentVolumeClaim:
            claimName: photoprism-claim2
        - name: photoprism-claim3
          persistentVolumeClaim:
            claimName: photoprism-claim3
status: {}
