apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-claim4
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 400Gi
status: {}
