apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  labels:
    io.kompose.service: photoprism-claim1
  name: photoprism-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10gb
status: {}
