apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostk3s-static-ghost2
  namespace: ghostk3s
  labels:
    app: ghostk3s
spec:
  storageClassName: nfs-csi # Change this to your storageClassName
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Change this to your accessModes
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ghostk3s2
  namespace: ghostk3s
  labels:
    app: mysql-ghostk3s
spec:
  storageClassName: nfs-csi # Change this to your storageClassName
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Change this to your accessModes
  resources:
    requests:
      storage: 1Gi
